# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 计算的本质
email: m0ur3n@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这是我的博客。因为太过喜欢《计算的本质》(Understanding Computation) 这本书，所以在想
  网站名字的时候，索性就用了这个。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m0ur3n.github.io" # the base hostname & protocol for your site
twitter_username: m0ur3n
github_username:  m0ur3n

# Build settings
markdown: kramdown
